services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   # the multi-stage one you wrote
    container_name: my-nginx
    ports:
      - "80:80"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: my-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/conf/custom.ini:/usr/share/grafana/conf/custom.ini
    environment:
      - GF_PATHS_CONFIG=/usr/share/grafana/conf/custom.ini
    restart: unless-stopped
