services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   # the multi-stage one you wrote
    container_name: my-nginx
    ports:
      - "80:80"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: my-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/conf/custom.ini:/usr/share/grafana/conf/custom.ini
    environment:
      - GF_PATHS_CONFIG=/usr/share/grafana/conf/custom.ini
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123123drink
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: my-telegraf
    env_file:
      - ./influxdb/telegraf/telegraf.env
    volumes:
      - ./influxdb/telegraf/room01.conf:/etc/telegraf/telegraf.conf:ro


  influxdb2:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-service/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
  
  mqtt-publisher:
    build:
      context: ./mqtt-service/publisher
      dockerfile: Dockerfile
    container_name: dummy-sensor
    depends_on:
      - mqtt
    restart: unless-stopped

secrets:
  influxdb2-admin-username:
    file: ./influxdb/docker-secrets/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./influxdb/docker-secrets/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./influxdb/docker-secrets/.env.influxdb2-admin-token

volumes:
  influxdb2-data:
  influxdb2-config: